services:
  - type: web
    name: sustainable-food-management
    runtime: node
    branch: master
    buildCommand: "cd client && npm install --include=dev && npm run build && cd ../server && npm install"
    startCommand: "cd server && node server.js"
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
